apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orion-plugin
  labels:
    k8s-app: virtaitech
spec:
  selector:
    matchLabels:
      name: orion-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: orion-plugin
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: virtaitech/orion-plugin:latest
        name: orion-plugin
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
        env:
        - name : ORION_CONTROLLER
          value : "172.17.0.1:9123"
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
